### ISSUE TITLE
git pull-request crashing

### ISSUE THREAD

**Issue by nicks** [dpup/git-workflow#15]
```
Traceback (most recent call last):
  File "/home/nick/src/git-workflow/git-pull-request", line 137, in <module>
    reviewer_list = alias_reviewers(reviewer_list, get_reviewer_aliases(repo))
  File "/home/nick/src/git-workflow/git-pull-request", line 36, in get_reviewer_aliases
    kv_pairs = reader.items("gitworkflow \"alias\"")
  File "/home/nick/.local/lib/python2.7/site-packages/git/config.py", line 508, in items
    return [(k, v) for k, v in super(GitConfigParser, self).items(section_name) if k != '__name__']
  File "/usr/lib/python2.7/ConfigParser.py", line 347, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'gitworkflow "alias"'
```

**Comment by nicks** [comment]
i don't know why this didn't get auto-closed when i fixed it!
